before_install:
  - sudo add-apt-repository --yes ppa:dirk-computer42/c42-builddeps
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgphoto2-6-dev
  - npm i nan
install:
  - npm run preinstall
script:
  - util/cpplint.sh
  - npm install
language: node_js
node_js:
  - 0.10
  - 0.11
  - 0.12
  - 6.10.0
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
